name: sync
description: a package template
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.4

dependencies:
  claudare_logging: ^1.0.0
  claudare_crypto: ^1.0.0
  cqrs: ^1.0.0
  isolate_sqlite: ^0.3.1
  stream_channel: ^2.1.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
