# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the recommended lint set for Flutter apps and Dart packages.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - camel_case_types
    - depend_on_referenced_packages
    - prefer_single_quotes
    - unawaited_futures

analyzer:
  errors:
    avoid_print: warning
    unawaited_futures: error
    dead_null_aware_expression: error
    unnecessary_non_null_assertion: error

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
