name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  mutex: ^3.1.0
  isolate_sqlite:
    git:
      url: git@github.com:claudare/isolate_sqlite.git
      ref: 0.3.1
dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
