name: claudare_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - apps/*
  - packages/*

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^8.2.2

melos:
  sdkPath: .fvm/flutter_sdk
  ide:
    intellij:
      enabled: false
  scripts:
    test:
      description: Run all workspace tests.
      steps:
        - test:dart
        - test:flutter
    test:dart:
      private: true
      exec:
        command: dart test --reporter failures-only
        failFast: true
      packageFilters:
        flutter: false
    test:flutter:
      private: true
      exec:
        command: flutter test --no-pub --reporter failures-only
        failFast: true
      packageFilters:
        flutter: true
