name: notes_app
description: Note application cqrs.
version: 0.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.4

dependencies:
  common: ^1.0.0
  cqrs: ^1.0.0
  crdt: ^1.0.0
  id_generator: ^1.0.0
  mutex: ^3.1.0

dev_dependencies:
  test: ^1.30.0
  time_provider: ^1.0.0
